# Generated by Django 4.2.11 on 2024-03-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "ordering": ["name"],
            },
        ),
    ]
